version: '3.8'
services:
  db:
    image: postgres:16.6
    container_name: common
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
volumes:
  pg_data:
