version: '3.8'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: common
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
volumes:
  pg_data:
